language: php
php:
    - "5.4"
    - "5.5"
before_script: composer install
script: phpunit --configuration vendor/playground/faq/phpunit.xml.dist
notifications:
    email:
        on_success: always
        on_failure: always