language: php
php:
    - "5.3"
    - "5.4"
before_script: composer install
script: phpunit --configuration vendor/playground/game/phpunit.xml.dist
notifications:
    email:
        on_success: always
        on_failure: always